"""Add query column to SearchHistory

Revision ID: 5c18f7f60e7d
Revises: 64cad1d3108b
Create Date: 2025-07-24 12:34:23.366023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c18f7f60e7d'
down_revision: Union[str, None] = '64cad1d3108b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_history', sa.Column('query', sa.String(), nullable=False))
    op.add_column('search_history', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_column('search_history', 'platform')
    op.drop_column('search_history', 'searched_at')
    op.drop_column('search_history', 'query_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_history', sa.Column('query_text', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('search_history', sa.Column('searched_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('search_history', sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('search_history', 'timestamp')
    op.drop_column('search_history', 'query')
    # ### end Alembic commands ###
